// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArykB2I2HzGI0RUSsJ47pR0WDVxyNQkfE',
    appId: '1:409017158410:web:df8c5f4831aa6859a388f3',
    messagingSenderId: '409017158410',
    projectId: 'ai-campus-companion-413c3',
    authDomain: 'ai-campus-companion-413c3.firebaseapp.com',
    storageBucket: 'ai-campus-companion-413c3.firebasestorage.app',
    measurementId: 'G-M8QB5V2BW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVlgHcQRsvDRMh2PZNT_BF3xCaYWDlL4o',
    appId: '1:409017158410:android:10adecf38504a1e5a388f3',
    messagingSenderId: '409017158410',
    projectId: 'ai-campus-companion-413c3',
    storageBucket: 'ai-campus-companion-413c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__f6LsL5zy5Gd2hYO1GHg1Mb3PpBn458',
    appId: '1:409017158410:ios:e4d02e57efc902dda388f3',
    messagingSenderId: '409017158410',
    projectId: 'ai-campus-companion-413c3',
    storageBucket: 'ai-campus-companion-413c3.firebasestorage.app',
    iosBundleId: 'com.example.aiCampusCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC__f6LsL5zy5Gd2hYO1GHg1Mb3PpBn458',
    appId: '1:409017158410:ios:e4d02e57efc902dda388f3',
    messagingSenderId: '409017158410',
    projectId: 'ai-campus-companion-413c3',
    storageBucket: 'ai-campus-companion-413c3.firebasestorage.app',
    iosBundleId: 'com.example.aiCampusCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArykB2I2HzGI0RUSsJ47pR0WDVxyNQkfE',
    appId: '1:409017158410:web:6f2974a037e7675fa388f3',
    messagingSenderId: '409017158410',
    projectId: 'ai-campus-companion-413c3',
    authDomain: 'ai-campus-companion-413c3.firebaseapp.com',
    storageBucket: 'ai-campus-companion-413c3.firebasestorage.app',
    measurementId: 'G-H6PBTD810Q',
  );
}
