import 'package:firebase_auth/firebase_auth.dart'; import 'package:flutter/material.dart'; import '../services/firestore_service.dart';
class AdminPanelScreen extends StatefulWidget { const AdminPanelScreen({super.key}); @override State<AdminPanelScreen> createState()=>_AdminPanelScreenState(); }
class _AdminPanelScreenState extends State<AdminPanelScreen>{ final service=FirestoreService(); final annTitle=TextEditingController(), annDesc=TextEditingController(), annCategory=TextEditingController(text:'Campus'), annPriority=TextEditingController(text:'medium'), annTarget=TextEditingController(text:'All'); final resTitle=TextEditingController(), resDesc=TextEditingController(), resCategory=TextEditingController(text:'Useful Link'), resCourse=TextEditingController(), resLink=TextEditingController();
Future<void> addAnnouncement() async { if(annTitle.text.isEmpty||annDesc.text.isEmpty){showMessage('Please fill announcement title and description.'); return;} await service.addAnnouncement(title:annTitle.text, description:annDesc.text, category:annCategory.text, priority:annPriority.text, targetProgramme:annTarget.text, createdBy:FirebaseAuth.instance.currentUser?.uid??''); annTitle.clear(); annDesc.clear(); showMessage('Announcement added.'); }
Future<void> addResource() async { if(resTitle.text.isEmpty||resLink.text.isEmpty){showMessage('Please fill resource title and link.'); return;} await service.addResource(title:resTitle.text, description:resDesc.text, category:resCategory.text, courseCode:resCourse.text, linkUrl:resLink.text, uploadedBy:FirebaseAuth.instance.currentUser?.uid??''); resTitle.clear(); resDesc.clear(); resCourse.clear(); resLink.clear(); showMessage('Resource added.'); }
void showMessage(String msg){ if(!mounted)return; ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(msg))); }
Widget input(TextEditingController c,String label)=>Padding(padding: const EdgeInsets.only(bottom:10), child: TextField(controller:c, decoration: InputDecoration(labelText:label, border: const OutlineInputBorder())));
@override void dispose(){ for(final c in [annTitle,annDesc,annCategory,annPriority,annTarget,resTitle,resDesc,resCategory,resCourse,resLink]){c.dispose();} super.dispose();}
@override Widget build(BuildContext context)=>Scaffold(appBar: AppBar(title: const Text('Admin Panel')), body: ListView(padding: const EdgeInsets.all(16), children:[ const Text('Add Announcement', style: TextStyle(fontSize:20, fontWeight:FontWeight.bold)), const SizedBox(height:12), input(annTitle,'Title'), input(annDesc,'Description'), input(annCategory,'Category'), input(annPriority,'Priority: high / medium / low'), input(annTarget,'Target Programme'), ElevatedButton(onPressed:addAnnouncement, child: const Text('Save Announcement')), const Divider(height:40), const Text('Add Resource', style: TextStyle(fontSize:20, fontWeight:FontWeight.bold)), const SizedBox(height:12), input(resTitle,'Title'), input(resDesc,'Description'), input(resCategory,'Category'), input(resCourse,'Course Code'), input(resLink,'Link URL'), ElevatedButton(onPressed:addResource, child: const Text('Save Resource'))])); }
